"""Regression guard for the portfolio dashboard section navigation.

The dashboard snapshot is regenerated by the weekly portfolio ritual
(e.g. 2e1028e6bb introduced the section jump nav; 7962d91b09 refreshed the
2026-09-07 snapshot and renamed the nav class from ``jump-nav`` to ``nav``
and the New Idea Filter section id from ``decisions`` to ``ideas``). This
test therefore binds the page's single ``<nav>`` element, not a specific
class name, and expects the current section ids. It keeps the original
invariant: every section-navigation link must target an existing section,
and the page must expose exactly the expected section set.
"""

from html.parser import HTMLParser
from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]
DASHBOARD = ROOT / "dashboard" / "public" / "index.html"
EXPECTED_TARGETS = {"brief", "p0", "support", "hold", "ideas"}


class DashboardParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.ids = set()
        self.nav_targets = set()
        self.in_nav = False

    def handle_starttag(self, tag, attrs):
        values = dict(attrs)
        if values.get("id"):
            self.ids.add(values["id"])
        if tag == "nav":
            self.in_nav = True
        if self.in_nav and tag == "a" and values.get("href", "").startswith("#"):
            self.nav_targets.add(values["href"][1:])

    def handle_endtag(self, tag):
        if tag == "nav" and self.in_nav:
            self.in_nav = False


class DashboardNavigationTests(unittest.TestCase):
    def test_navigation_targets_existing_sections(self):
        parser = DashboardParser()
        parser.feed(DASHBOARD.read_text(encoding="utf-8"))

        self.assertEqual(parser.nav_targets, EXPECTED_TARGETS)
        self.assertTrue(EXPECTED_TARGETS.issubset(parser.ids))


if __name__ == "__main__":
    unittest.main()
