#!/usr/bin/env python3
"""EXP-19 / CP-02: render the existing experiment registry as a Reladraw diagram.

Read-only view layer. The single source of truth stays
`experiments/EXPERIMENT_REGISTRY.json`; this script only emits a derived
`.reladraw` text file (and never writes back to the registry).

Mapping:
  project        <- experiment.owning_project        (container)
  status column  <- experiment.status                (sub-container)
  experiment     <- experiment_id + name             (leaf)
  next step      <- experiment.next_action           (muted 2nd line, truncated)
  dependency     <- EXP-ids mentioned in why/next_action/result_summary
                    (INFERRED from free text: the registry has no depends_on field)

Usage:
  python scripts/registry_to_reladraw.py [--registry PATH] [--out PATH] [--next-chars N]
Render (optional, external tool, not a dependency of MPE):
  npx reladraw@0.13.0 OUT.reladraw -o OUT.svg
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REGISTRY = ROOT / "experiments" / "EXPERIMENT_REGISTRY.json"
STATUS_ORDER = ["PASS", "READY_TO_TEST", "PLANNED", "HOLD", "PARTIAL", "BLOCKED", "FAIL"]
STATUS_STYLE = {
    "PASS": "st_pass",
    "READY_TO_TEST": "st_ready",
    "PLANNED": "st_planned",
    "HOLD": "st_hold",
}
EXP_ID = re.compile(r"EXP-[A-Z0-9]+(?:-[A-Z0-9]+)*")


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_") or "x"


def esc(text: str) -> str:
    # Reladraw text escapes: quote, backslash, spaced slash (line break marker), '['.
    text = text.replace("\\", "\\\\").replace('"', '\\"').replace("[", "\\[")
    return text.replace(" / ", " \\/ ")


def short(text: str, n: int) -> str:
    text = " ".join(text.split())
    return text if len(text) <= n else text[: n - 1].rstrip() + "…"


def inferred_dependencies(experiments: list[dict]) -> list[tuple[str, str]]:
    ids = {e["experiment_id"] for e in experiments}
    deps = []
    for e in experiments:
        blob = " ".join(str(e.get(k, "")) for k in ("why", "next_action", "result_summary"))
        for ref in sorted(set(EXP_ID.findall(blob))):
            if ref in ids and ref != e["experiment_id"]:
                deps.append((e["experiment_id"], ref))
    return deps


def build(registry: dict, next_chars: int = 48) -> str:
    exps = registry["experiments"]
    projects: dict[str, dict[str, list[dict]]] = {}
    for e in exps:
        projects.setdefault(e["owning_project"], {}).setdefault(e["status"], []).append(e)

    node_of: dict[str, str] = {}
    out = [
        "// GENERATED by scripts/registry_to_reladraw.py — do not edit by hand.",
        f"// source: experiments/EXPERIMENT_REGISTRY.json (updated_at {registry.get('updated_at', '?')})",
        "diagram  theme: light",
        "style st_pass     fill: #dcfce7  border: #16a34a",
        "style st_ready    fill: #dbeafe  border: #2563eb",
        "style st_planned  fill: #f3f4f6  border: #6b7280",
        "style st_hold     fill: #fef3c7  border: #d97706",
        "style col         contents: (widths: match)",
        "",
    ]
    # Largest project first; others stacked below it (keeps width bounded).
    order = sorted(projects, key=lambda p: -sum(len(v) for v in projects[p].values()))
    prev_proj = None
    for proj in order:
        p = "p_" + slug(proj)
        place = f"  below {prev_proj}" if prev_proj else ""
        out.append(f'node {p} "{esc(proj)}"{place}')
        prev_col = None
        statuses = sorted(projects[proj], key=lambda s: STATUS_ORDER.index(s) if s in STATUS_ORDER else 99)
        for status in statuses:
            c = f"{p}.{slug(status)}"
            items = projects[proj][status]
            cplace = f"  right of {prev_col}  level with {prev_col}" if prev_col else ""
            out.append(f'node {c} "{status} ({len(items)})"  style: col{cplace}')
            for e in items:
                n = f"{c}.{slug(e['experiment_id'])}"
                node_of[e["experiment_id"]] = n
                nxt = short(e.get("next_action", ""), next_chars)
                line1 = esc(e["experiment_id"])
                line2 = esc(short(e["name"], 30))
                line3 = esc("→ " + nxt)
                out.append(
                    f'node {n} "{line1} / {line2} / {line3}" (wrap: 34)'
                    f"  style: {STATUS_STYLE.get(status, 'st_planned')}"
                )
            prev_col = c
        prev_proj = p
        out.append("")

    deps = inferred_dependencies(exps)
    if deps:
        out.append("// dependencies INFERRED from free text (no depends_on field in registry)")
    for src, dst in deps:
        out.append(f'edge {node_of[src]} -> {node_of[dst]}  "waits on"  line: (pattern: dashed)')
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    ap.add_argument("--out", type=Path, default=None)
    ap.add_argument("--next-chars", type=int, default=48)
    a = ap.parse_args(argv)
    text = build(json.loads(a.registry.read_text(encoding="utf-8")), a.next_chars)
    if a.out:
        a.out.parent.mkdir(parents=True, exist_ok=True)
        a.out.write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
